In [1]:
#from google.colab import drive
#drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
#cd /content/drive/MyDrive/

/content/drive/MyDrive


In [2]:
pip install librosa

  Created wheel for audioread: filename=audioread-2.1.9-py3-none-any.whl size=23141 sha256=8e66d82a06734680a2b3d8fbeda35be8855dbd54b523a2f9da667b37fc0949ff
  Stored in directory: c:\users\jafsi\appdata\local\pip\cache\wheels\ba\7b\eb\213741ccc0678f63e346ab8dff10495995ca3f426af87b8d88
  Created wheel for resampy: filename=resampy-0.2.2-py3-none-any.whl size=320718 sha256=d27bbeb2d699707b17e120154c2596617ac4b86ac6c439580f9245fca92d5d36
  Stored in directory: c:\users\jafsi\appdata\local\pip\cache\wheels\a0\18\0a\8ad18a597d8333a142c9789338a96a6208f1198d290ece356c
Successfully built audioread resampy
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\JaFsi\anaconda3\python.exe -m pip install --upgrade pip' command.


In [3]:
import pandas as pd
import os
import librosa              # used for audio processing
import librosa.display
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
import tensorflow as tf
from tensorflow.keras.layers import LSTM, Dense
from keras.preprocessing import sequence
from keras.models import Sequential
from sklearn.preprocessing import LabelBinarizer
import numpy as np

In [6]:
X=[]
Y=[]
for folder in os.scandir('./Audio'):
    for file in os.scandir(folder.path):
        print(file.name)
        y,sr=librosa.load(file.path)
        X.append(y)
        Y.append(folder.name)
        print(y.shape)

8770-295462-0010.wav
(315977,)
8770-295462-0011.wav
(267026,)
8770-295462-0012.wav
(305834,)
8770-295462-0013.wav
(285658,)
8770-295462-0014.wav
(344311,)
8770-295462-0020.wav
(268017,)
8770-295462-0021.wav
(302859,)
8770-295462-0022.wav
(312008,)
8770-295462-0023.wav
(295360,)
8770-295462-0024.wav
(259308,)
8770-295462-0025.wav
(312008,)
8770-295462-0026.wav
(327994,)
8770-295462-0027.wav
(267357,)
8770-295462-0028.wav
(342327,)
8770-295462-0029.wav
(318954,)
8770-295462-0037.wav
(303298,)
8770-295462-0038.wav
(318513,)
8770-295462-0039.wav
(320277,)
8770-295462-0040.wav
(132190,)
8770-295462-0041.wav
(137592,)
8797-294123-0000.wav
(74750,)
8797-294123-0001.wav
(320277,)
8797-294123-0002.wav
(265703,)
8797-294123-0013.wav
(307157,)
8797-294123-0014.wav
(325569,)
8797-294123-0015.wav
(303739,)
8797-294123-0016.wav
(301644,)
8797-294123-0017.wav
(321820,)
8797-294123-0023.wav
(282571,)
8797-294123-0024.wav
(326451,)
8797-294123-0025.wav
(313662,)
8797-294123-0026.wav
(197679,)
8797-2941

In [7]:
enc = LabelBinarizer()
max_review_length = 30000
X_tr = sequence.pad_sequences(X, maxlen=max_review_length)[:30000]
print(X_tr.shape)
X_tr = X_tr.reshape( X_tr.shape[0], X_tr.shape[1],-1)
print(X_tr.shape)
Y = enc.fit(Y).transform(Y)

(60, 30000)
(60, 30000, 1)


In [ ]:
#X_tr = np.array(X_tr, dtype=np.float32) # if we need convert to float

In [ ]:
modelClass = Sequential()
modelClass.add(LSTM(100, input_shape=(30000,1)))
modelClass.add(Dense(3, activation='softmax')) # categorical
modelClass.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print(modelClass.summary())
modelClass.fit(X_tr, Y, epochs=10, batch_size=1)

scores = modelClass.evaluate(X_tr, Y, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 100)               40800     
_________________________________________________________________
dense (Dense)                (None, 3)                 303       
Total params: 41,103
Trainable params: 41,103
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/10
60/60 [==============================] - ETA: 0s - loss: 1.1076 - accuracy: 0.283 - 2105s 35s/step - loss: 1.1076 - accuracy: 0.2833
Epoch 2/10
50/60 [========================>.....] - ETA: 5:42 - loss: 1.1022 - accuracy: 0.2400

In [7]:
print(Y)

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]]
